<?php
// This file was auto-generated by the i18n change. Please review manually.

return [

    'shared' => [
        'detail'   => 'Detail',
        'back'     => 'Back',
        'students' => 'Students',
    ],

    'home' => [
        'latest_info'            => 'Latest Information',
        'latest_competitions'    => 'Latest Competitions',
        'competitions_desc'      => 'Join prestigious competitions and achieve your best at national and international levels',
        'view_all_competitions'  => 'View All Competitions',
        'scholarship_info'       => 'Scholarship Information',
        'scholarship_desc'       => 'Find various scholarship opportunities to support your academic journey',
        'view_all_scholarship'   => 'View All Scholarships',
        'quick_access'           => 'Quick Access',
        'quick_access_desc'      => 'Find the information you need with one click',
        'ormawa_desc'            => 'Explore various student organizations, UKMs, and communities at Polban',
        'competitions_card_desc' => 'Latest academic and non-academic competition information to sharpen your skills',
        'scholarship_card_desc'  => 'Various internal and external scholarship options to help fund your studies',
    ],

    'beasiswa' => [
        'subtitle'           => 'Scholarship Information for Polban Students',
        'search_label'       => 'Search Scholarship',
        'search_placeholder' => 'Scholarship name...',
        'major_label'        => 'Major',
        'major_placeholder'  => 'Filter by major...',
        'type_label'         => 'Scholarship Type',
        'kind_label'         => 'Scholarship Kind',
        'status_label'       => 'Scholarship Status',
        'status_ongoing'     => 'Ongoing',
        'status_upcoming'    => 'Upcoming',
        'status_ended'       => 'Ended',
        'no_results'         => 'No scholarships found',
        'poster_alt'         => 'Scholarship Poster',
        'register_now'       => 'Register Now',
        'view_detail'        => 'View Detail',
        'detail_type'        => 'Type',
        'detail_kind'        => 'Kind',
        'detail_quota'       => 'Quota',
        'detail_source'      => 'Scholarship Source',
        'detail_deadline'    => 'Registration Deadline',
        'benefit'            => 'Benefit',
        'requirement'        => 'Requirements',
        'required_docs'      => 'Required Documents',
        'recipients'         => 'Scholarship Recipients',
        'nim'                => 'NIM',
        'student_name'       => 'Student Name',
        'study_program'      => 'Study Program',
    ],

    'competition' => [
        'subtitle' => 'National and International Competitions',
        'search_placeholder' => 'Search competitions, organizers, or other keywords...',
        'status_ongoing' => 'Ongoing',
        'status_closed' => 'Registration Closed',
        'status_completed' => 'Completed',
        'registration' => 'Registration',
        'timeline_heading' => 'Competition Timeline',
        'location' => 'Location',
        'contact' => 'Contact Person',
        'btn_detail' => 'Detail Info',
        'btn_register' => 'Registration Link',
        'btn_guidebook' => 'Guidebook / Technical Guide',
        'load_error' => 'Failed to load competitions',
    ],

    'ormawa' => [
        'subtitle'         => 'Student Organizations and Activity Units',
        'no_content'       => 'Detailed information for :name will be available soon.',
        'org_list_heading' => ':name - Organization List',
    ],

    'profile' => [
        'no_content' => 'Content for this page is not yet available.',
    ],

    'services' => [
        'no_content'          => 'Details for this service are being prepared.',
        'proceed_to_service'  => 'Proceed to Service',
        'external_notice'     => 'This service is accessed through an external page. Click the button to open in a new tab.',
        'further_links'       => 'Further Links',
        'documents_downloads' => 'Documents & Downloads',
        'open_download_doc'   => 'Open / download document',
        'need_help'           => 'Need Help?',
        'contact_unit_info'   => 'Contact the relevant unit for more information about this service.',
        'contact_us'          => 'Contact Us',
    ],

    'downloads' => [
        'title'              => 'Download Center & Documents',
        'heading'            => 'Downloads',
        'subtitle'           => 'Find various documents, forms, and certificates you need here.',
        'categories'         => 'Categories',
        'all_documents'      => 'All Documents',
        'search_placeholder' => 'Search documents...',
        'showing_items'      => 'Showing :from - :to of :total documents',
        'keyword_prefix'     => 'Keyword:',
        'download_btn'       => 'Download',
        'detail_btn'         => 'Detail',
        'not_found'          => 'Document Not Found',
        'no_docs'            => 'No Documents Yet',
        'search_no_match'    => 'Sorry, no documents match the keyword ":keyword".',
        'no_docs_category'   => 'Sorry, there are currently no documents available for this category.',
        'clear_search'       => 'Clear Search',
        'preview_title'      => 'Document Preview',
        'no_preview'         => 'Preview not available for this file type',
        'download_to_view'   => 'Please download the document to view its contents.',
        'doc_info'           => 'Document Information',
        'doc_name'           => 'Document Name',
        'last_updated'       => 'Last Updated',
        'file_size'          => 'File Size',
        'file_type'          => 'File Type',
        'download_now'       => 'Download Now',
        'fullscreen_mode'    => 'Fullscreen Mode',
    ],

    'banner' => [
        'previous' => 'Previous',
        'next'     => 'Next',
    ],

    'footer' => [
        'org_name'            => 'Directorate of Student Affairs and Alumni',
        'org_parent'          => 'Politeknik Negeri Bandung',
        'all_rights_reserved' => 'All rights reserved.',
    ],

    'nav' => [
        'no_pages'    => 'No pages available',
        'no_services' => 'No services available',
    ],

    'video' => [
        'invalid_url' => 'Invalid video URL',
    ],

    'filament_poster' => [
        'category'   => 'Category',
        'title'      => 'Title',
        'created_at' => 'Created',
    ],

];
