<?php
// This file was auto-generated by the i18n change. Please review manually.

return [

    // -------------------------------------------------------------------------
    // Shared strings used across multiple pages
    // -------------------------------------------------------------------------
    'shared' => [
        'detail'   => 'Detail',
        'back'     => 'Kembali',
        'students' => 'Mahasiswa',
    ],

    // -------------------------------------------------------------------------
    // Home page
    // -------------------------------------------------------------------------
    'home' => [
        'latest_info'           => 'Informasi Terbaru',
        'latest_competitions'   => 'Kompetisi Terbaru',
        'competitions_desc'     => 'Ikuti kompetisi bergengsi dan raih prestasimu di tingkat nasional maupun internasional',
        'view_all_competitions' => 'Lihat Semua Kompetisi',
        'scholarship_info'      => 'Informasi Beasiswa',
        'scholarship_desc'      => 'Temukan berbagai peluang beasiswa untuk mendukung perjalanan akademikmu',
        'view_all_scholarship'  => 'Lihat Semua Beasiswa',
        'quick_access'          => 'Akses Cepat',
        'quick_access_desc'     => 'Temukan informasi yang kamu butuhkan dengan satu klik',
        'ormawa_desc'           => 'Jelajahi berbagai organisasi mahasiswa, UKM, dan komunitas di lingkungan Polban',
        'competitions_card_desc' => 'Informasi kompetisi akademik dan non-akademik terbaru untuk mengasah bakatmu',
        'scholarship_card_desc' => 'Berbagai pilihan beasiswa internal maupun eksternal untuk membantu pembiayaan kuliah',
    ],

    // -------------------------------------------------------------------------
    // Beasiswa (Scholarship) pages
    // -------------------------------------------------------------------------
    'beasiswa' => [
        // Index page
        'subtitle'          => 'Informasi Beasiswa untuk Mahasiswa Polban',
        'search_label'      => 'Cari Beasiswa',
        'search_placeholder' => 'Nama beasiswa...',
        'major_label'       => 'Jurusan',
        'major_placeholder' => 'Filter jurusan...',
        'type_label'        => 'Tipe Beasiswa',
        'kind_label'        => 'Jenis Beasiswa',
        'status_label'      => 'Status Beasiswa',
        'status_ongoing'    => 'Berjalan',
        'status_upcoming'   => 'Akan Datang',
        'status_ended'      => 'Selesai',
        'no_results'        => 'Tidak ada beasiswa ditemukan',
        'poster_alt'        => 'Poster Beasiswa',
        'register_now'      => 'Daftar Sekarang',
        'view_detail'       => 'Lihat Detail',
        // Detail page
        'detail_type'       => 'Tipe',
        'detail_kind'       => 'Jenis',
        'detail_quota'      => 'Kuota',
        'detail_source'     => 'Sumber Beasiswa',
        'detail_deadline'   => 'Batas Akhir Pendaftaran',
        'benefit'           => 'Benefit',
        'requirement'       => 'Syarat',
        'required_docs'     => 'Dokumen Diperlukan',
        'recipients'        => 'Penerima Beasiswa',
        'nim'               => 'NIM',
        'student_name'      => 'Nama Mahasiswa',
        'study_program'     => 'Prodi',
    ],

    // -------------------------------------------------------------------------
    // Competition page
    // -------------------------------------------------------------------------
    'competition' => [
        'subtitle' => 'Kompetisi Nasional dan Internasional',
        'search_placeholder' => 'Cari kompetisi, penyelenggara, atau kata kunci lainnya...',
        'status_ongoing' => 'Sedang Berlangsung',
        'status_closed' => 'Pendaftaran Ditutup',
        'status_completed' => 'Selesai',
        'registration' => 'Registrasi',
        'timeline_heading' => 'Timeline Kompetisi',
        'location' => 'Lokasi',
        'contact' => 'Kontak Persona',
        'btn_detail' => 'Detail Info',
        'btn_register' => 'Link Pendaftaran',
        'btn_guidebook' => 'Guidebook / Juknis',
        'load_error' => 'Gagal memuat kompetisi',
    ],

    // -------------------------------------------------------------------------
    // Ormawa (Student Organizations) pages
    // -------------------------------------------------------------------------
    'ormawa' => [
        'subtitle'          => 'Organisasi Mahasiswa dan Unit Kegiatan Mahasiswa',
        'no_content'        => 'Informasi detail untuk :name akan segera tersedia.',
        'org_list_heading'  => ':name - Daftar Organisasi',
    ],

    // -------------------------------------------------------------------------
    // Profile page
    // -------------------------------------------------------------------------
    'profile' => [
        'no_content' => 'Konten untuk halaman ini belum tersedia.',
    ],

    // -------------------------------------------------------------------------
    // Services page
    // -------------------------------------------------------------------------
    'services' => [
        'no_content'          => 'Detail untuk layanan ini sedang kami lengkapi.',
        'proceed_to_service'  => 'Lanjut ke Layanan',
        'external_notice'     => 'Layanan ini diakses melalui halaman eksternal. Klik tombol untuk membuka di tab baru.',
        'further_links'       => 'Tautan Lanjutan',
        'documents_downloads' => 'Dokumen & Unduhan',
        'open_download_doc'   => 'Buka / unduh dokumen',
        'need_help'           => 'Butuh Bantuan?',
        'contact_unit_info'   => 'Hubungi unit terkait untuk informasi lebih lanjut tentang layanan ini.',
        'contact_us'          => 'Hubungi Kami',
    ],

    // -------------------------------------------------------------------------
    // Downloads pages
    // -------------------------------------------------------------------------
    'downloads' => [
        // Index page
        'title'             => 'Pusat Unduhan & Dokumen',
        'heading'           => 'Unduhan',
        'subtitle'          => 'Temukan berbagai dokumen, formulir, dan sertifikat yang Anda butuhkan di sini.',
        'categories'        => 'Kategori',
        'all_documents'     => 'Semua Dokumen',
        'search_placeholder' => 'Cari dokumen...',
        'showing_items'     => 'Menampilkan :from - :to dari :total dokumen',
        'keyword_prefix'    => 'Kata kunci:',
        'download_btn'      => 'Unduh',
        'detail_btn'        => 'Detail',
        'not_found'         => 'Dokumen Tidak Ditemukan',
        'no_docs'           => 'Belum Ada Dokumen',
        'search_no_match'   => 'Maaf, tidak ada dokumen yang cocok dengan kata kunci ":keyword".',
        'no_docs_category'  => 'Maaf, saat ini belum ada dokumen tersedia untuk kategori ini.',
        'clear_search'      => 'Bersihkan Pencarian',
        // Show (detail) page
        'preview_title'     => 'Pratinjau Dokumen',
        'no_preview'        => 'Pratinjau tidak tersedia untuk tipe file ini',
        'download_to_view'  => 'Silakan unduh dokumen untuk melihat isinya.',
        'doc_info'          => 'Informasi Dokumen',
        'doc_name'          => 'Nama Dokumen',
        'last_updated'      => 'Tanggal Diperbarui',
        'file_size'         => 'Ukuran File',
        'file_type'         => 'Tipe File',
        'download_now'      => 'Unduh Sekarang',
        'fullscreen_mode'   => 'Mode Layar Penuh',
    ],

    // -------------------------------------------------------------------------
    // Banner slider component
    // -------------------------------------------------------------------------
    'banner' => [
        'previous' => 'Sebelumnya',
        'next'     => 'Selanjutnya',
    ],

    // -------------------------------------------------------------------------
    // Footer component
    // -------------------------------------------------------------------------
    'footer' => [
        'org_name'           => 'Direktorat Kemahasiswaan dan Alumni',
        'org_parent'         => 'Politeknik Negeri Bandung',
        'all_rights_reserved' => 'Hak cipta dilindungi.',
    ],

    // -------------------------------------------------------------------------
    // Navigation component
    // -------------------------------------------------------------------------
    'nav' => [
        'no_pages'    => 'Belum ada halaman',
        'no_services' => 'Belum ada layanan',
    ],

    // -------------------------------------------------------------------------
    // Video player component
    // -------------------------------------------------------------------------
    'video' => [
        'invalid_url' => 'URL video tidak valid',
    ],

    // -------------------------------------------------------------------------
    // Filament admin infolist: poster-meta
    // -------------------------------------------------------------------------
    'filament_poster' => [
        'category'   => 'Kategori',
        'title'      => 'Judul',
        'created_at' => 'Dibuat',
    ],

];
